image: Visual Studio 2019
install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: >-
      $version = ConvertFrom-Json $($(GitVersion) -join "")
      
      $content = Get-Content .\Version.template.props -Raw;
      $content = $content.Replace("&InformationalVersion&", $version.InformationalVersion);
      $content = $content.Replace("&FileVersion&", $version.AssemblySemFileVer);
      $content = $content.Replace("&AssemblyVersion&", $version.AssemblySemVer);
      $content = $content.Replace("&NugetVersion&", $version.NuGetVersion);
      Set-Content .\Version.props $content;
      
      Update-AppveyorBuild -Version $version.NuGetVersion
  - msbuild /t:Restore /Verbosity:Minimal

build_script:
  - cmd: msbuild /t:build /p:Configuration=Release /Verbosity:Minimal

test_script:
  - cmd: dotnet test Tests\LibraryTests\LibraryTests.csproj -c Release --no-build --logger:trx -- RunConfiguration.TargetPlatform="x64" RunConfiguration.DisableParallelization="true"

artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.snupkg'

after_test:
  - cmd: msbuild /t:pack /p:Configuration=Release /p:IncludeSymbols=true /Verbosity:Minimal /p:NoBuild=true

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/discutils/api/v2/package
    api_key:
      secure: foGROcPrYEku4LqHLdwidY8kXnpLsAB1YOBufMY0P9AptYpUzySgx5gezRcZ9vma
    on:
      # We push on all develop commits
      branch: develop
  
  - provider: NuGet
    api_key:
      secure: 1zdVvAQJbpFDsKJS/TXQLc6GI6SlZueTSCcL7xbK6QMisvL8V5nhLFgrceLfp1Ak
    on:
      # Only push on tagged master commits
      branch: master
      APPVEYOR_REPO_TAG: true
      
  - provider: GitHub
    description: 'Automated release from Appveyor'
    auth_token:
      secure: PzHMfZUHtddDN/+S4C0K6emflG2EpgynNlu/p/T4hizDb8M7UChpohLUSd4BkFRU
    artifact: /.*\.s?nupkg/
    draft: false
    prerelease: false
    on:
      # Only add releases on tagged master commits
      branch: master
      APPVEYOR_REPO_TAG: true
